### PR TITLE
Backport upstream deps

### PR DESCRIPTION
**Pull request by honza**
https://review.openstack.org/#/c/624376/1

### CODE REVIEW

**Review by apevec — APPROVED** [review]

**Comment by apevec** [comment]
@honza FYI running create-tarball.sh (on F29 with npm-6.4.1-1.10.13.0.1.fc29 / nodejs-10.13.0-1.fc29):
...
added 2192 packages from 1039 contributors and audited 24886 packages in 66.028s
found 987 vulnerabilities (853 low, 106 moderate, 27 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details

**Comment by honza** [comment]
Yes, I think we've encountered this before. TripleO-UI should be built with npm 5.6.0.

cc @jtomasek

**Comment by honza** [comment]
We're planning to upgrade to the newer version of npm at some point soon. We're limited by upstream CI. I believe npm 6.4.x is in the LTS so it shouldn't be a hard sell. 

Does it present a problem for you to use the older version of npm? Is there a way we can indicate that in the spec file?

**Comment by apevec** [comment]
Please add npm version check in create-tarball.sh, this runs first and creates a tarball with local npm,
and best to move this tarball creation to a container with correct npm version.
I've already pushed the build in CBS Koji http://cbs.centos.org/koji/buildinfo?buildID=24743
so I guess we'll have to scrap it? :(

**Comment by honza** [comment]
I'm not really sure if there are any adverse side effects to building with the new version. I just know we've seen those errors that you quoted. I'll work on adding the version check. Is there documentation available on the containerization of the build process?

**Comment by apevec** [comment]
ok let me know if http://cbs.centos.org/kojifiles/packages/openstack-tripleo-ui-deps/9/4.el7/noarch/openstack-tripleo-ui-deps-9-4.el7.noarch.rpm works

**Comment by apevec** [comment]
re. containerization, in short, it would be dockerfile extending centos, installing npm and other builld deps from RDO repo then running create-tarball script, nothing fancy

UPDATE quick unverified proposal: https://github.com/rdo-common/openstack-tripleo-ui-deps/pull/28

**Comment by jtomasek** [comment]
> @honza FYI running create-tarball.sh (on F29 with npm-6.4.1-1.10.13.0.1.fc29 / nodejs-10.13.0-1.fc29):
> ...
> added 2192 packages from 1039 contributors and audited 24886 packages in 66.028s
> found 987 vulnerabilities (853 low, 106 moderate, 27 high, 1 critical)
> run `npm audit fix` to fix them, or `npm audit` for details

I believe that building with this version of npm should not pose a problem. The warning is a hint on keeping the dependencies up to date.

+1 to fixing the npm version we build with

**Comment by honza** [comment]
It looks like 9.4 isn't available in the repo yet

https://trunk.rdoproject.org/centos7-rocky/build-deps/latest/noarch/

**Comment by apevec** [comment]
@honza  yeah please vote in deps update review https://review.rdoproject.org/r/17815

**Pull request merged**
